### ISSUE TITLE
View future days forecat (hourly weather + sunrise/sunset etc.)

### ISSUE THREAD

**Issue by DadiBit** [MisterF1x/WeatherAPP#2]
It would be nice to view the hourly forecast by clicking on a day of the week.
Personally, I have two concepts:
1. Left navbar, under the search bar, with weekly forecast, with the right panel offering the hourly plan and more details
2. Top navbar that shows the weekly forecast and the left/right panels like they are currently

**Comment by MisterF1x** [comment]
Thank you for your review. Good idea!
